# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Nguyen Minh Dan
#title: Hi, Nice to see you !
email: nguyenmd.works@gmail.com
website: nmdan.xyz

# Social links
github_username:  bill29
facebook_username: dan.minh336
instagram_username: nm_zan
# About Section
 #about_title: About Me 
about_profile_image: images/d.jpg
about_content: Hi , i am Dan. I am student of HUST . My major is Computer science. I am very funny and friendly. I love reading and playing sports. The club I like is Chelsea, my favorite athlete is Ronaldo, Nadal. You can connect my [Goodreads account](https://www.goodreads.com/user/show/90677782-d-n-nguy-n).
# Projects Section
#projects_title: abc

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
#more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]